backend:
  name: github
  repo: patternli/next # Path to your GitHub repository
  netlify.configure({'site_id': nextlibrary.netlify.app);
  # optional, defaults to master
  branch: main

media_folder: "assets/img/uploads"